exports.seed = (knex, Promise) => {
  const tableName = 'graph_data';
  const data = [{
    department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 74,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 80,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 77,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 77,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 88,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 83,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    grade: 86,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 97,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 75,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 95,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 91,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 98,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 91,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 82,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 90,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 94,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 94,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 84,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 72,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    grade: 83,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 76,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 77,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 92,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 79,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 96,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    grade: 92,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 75,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 78,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 76,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 81,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 82,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 83,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 86,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 90,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 91,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 98,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 78,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    grade: 74,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 72,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 92,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 69,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 85,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    grade: 81,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 70,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 82,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 92,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 66,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 83,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 97,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    grade: 71,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 66,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 84,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 85,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 72,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 96,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 74,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    grade: 80,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 84,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 88,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 96,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 86,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 90,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 70,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    grade: 69,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 82,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 98,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 99,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 88,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 94,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 73,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 83,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 96,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 99,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 74,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 76,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 100,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 94,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 76,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    grade: 90,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 90,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 84,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 99,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 81,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 68,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 80,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    grade: 100,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 80,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 91,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 72,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 73,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 81,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    grade: 88,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 80,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 66,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 67,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 95,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    grade: 99,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 71,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 69,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 79,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 89,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 70,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    grade: 86,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 92,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 99,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 73,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 86,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 91,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 77,
    student_id: 7 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    grade: 78,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 81,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 83,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    grade: 83,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 95,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 67,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 76,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 83,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 66,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 93,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 78,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 99,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 92,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 80,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 84,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 80,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 81,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 74,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    grade: 98,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 91,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 70,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 95,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 88,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 78,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 100,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 95,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 90,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 84,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 88,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 76,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 66,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    grade: 90,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 80,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 82,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 65,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 66,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 68,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    grade: 88,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 94,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 86,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 90,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 79,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 79,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    grade: 99,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 65,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 85,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 93,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 93,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 92,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    grade: 86,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 78,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 98,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 70,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    grade: 67,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 67,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 83,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 85,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 97,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    grade: 92,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 80,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 76,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 73,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    grade: 86,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 88,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 84,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 79,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    grade: 65,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 74,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 73,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 95,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 99,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 99,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 75,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 70,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 83,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    grade: 90,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 88,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 84,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 93,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 68,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    grade: 85,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 71,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 81,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 72,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 100,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 96,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    grade: 70,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 71,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 77,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 91,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 89,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 99,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 81,
    student_id: 7 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    grade: 90,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 92,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 91,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 86,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 65,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 92,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 66,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    grade: 84,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 67,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 81,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 71,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 82,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    grade: 77,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 83,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 71,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 77,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 85,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 83,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    grade: 91,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 86,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 95,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 93,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 69,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 72,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 83,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 83,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 66,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 93,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 91,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 99,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 80,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 70,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    grade: 70,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 72,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 93,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 69,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 84,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 70,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 81,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    grade: 70,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 66,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 80,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 98,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 75,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 69,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 95,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 65,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 85,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 90,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 76,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 82,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 73,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 94,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    grade: 94,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 97,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 99,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 82,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 100,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 84,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 82,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 93,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    grade: 86,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 95,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 99,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 92,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 76,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    grade: 80,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 90,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 69,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 80,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 98,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 77,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 96,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    grade: 78,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 97,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 98,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 87,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 76,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 76,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 71,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 73,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 92,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 77,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    grade: 93,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 75,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 84,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 86,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 90,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 69,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 89,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 70,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 92,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 67,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 73,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 99,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 91,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    grade: 74,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 99,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 83,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 86,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 88,
    student_id: 7 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    grade: 93,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 68,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 95,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 95,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 80,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 68,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 89,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 83,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 76,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 99,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 70,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 69,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 93,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    grade: 82,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 80,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 66,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 68,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 95,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 66,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 100,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 70,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 78,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    grade: 71,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 73,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 87,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 72,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 76,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 66,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 65,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 86,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    grade: 69,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 77,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 76,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 78,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 89,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 72,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    grade: 92,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 73,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 92,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 88,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 76,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 71,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 89,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    grade: 91,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 92,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 84,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 69,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 70,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 91,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 84,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    grade: 79,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 69,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 83,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 81,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 88,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    grade: 83,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 93,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 98,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 85,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 95,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 71,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 76,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    grade: 97,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 87,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 72,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 68,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 99,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 97,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    grade: 89,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 66,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 87,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 69,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 89,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 94,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    grade: 73,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 99,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 74,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 70,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 96,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 90,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    grade: 71,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 72,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 91,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 67,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 92,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 88,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 78,
    student_id: 7 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    grade: 65,
    student_id: 7 }];

  return knex(tableName).del()
    .then(() => Promise.all(data.map(type => knex(tableName).insert(type))));
};
