exports.seed = (knex, Promise) => {
  const departmentsTable = 'departments';
  const coursesTable = 'courses';
  const userTypesTable = 'users_types';
  const usersTable = 'users';
  const calendarTable = 'calendar';
  const classesTable = 'classes';
  const modulesTable = 'modules';
  const studentClassTable = 'students_classes';
  const gradeableObjectTypesTable = 'gradeable_objects_types';
  const gradeableObjectsTable = 'gradeable_objects';
  const meetingsTable = 'meetings';
  const attendanceTable = 'attendance';
  const graphTable = 'graph_data';

  const tableData = ['departments', 'courses', 'users_types', 'users', 'classes', 'calendar', 'modules', 'meetings', 'gradeable_objects_types', 'gradeable_objects', 'meetings', 'graph_data'];

  const departmentData = [
    {
      id: 1,
      name: 'English',
    },
    {
      id: 2,
      name: 'Math',
    },
    {
      id: 3,
      name: 'Science',
    },
    {
      id: 4,
      name: 'Modern Languages',
    },
  ];

  const courseData = [
    {
      id: 1,
      department_id: '1',
      name: 'American Literature',
      description: 'This course covers American Literature from the Pre-Columbian era, to the early American writers, through the industrial revolution and ending in the mid-20th Century.',
    },
    {
      id: 2,
      department_id: '2',
      name: 'Pre-Algebra',
      description: 'This course covers Trigonometry, Geometry, Algebra and Statistics.',
    },
    {
      id: 3,
      department_id: '3',
      name: 'Biology',
      description: 'This course covers Scientific Method, Characteristics of Life, Cells and Cell Processes and Genetics and DNA.',
    },
    {
      id: 4,
      department_id: '4',
      name: 'Spanish',
      description: 'This course covers Beginning, Intermediate and Advanced Spanish.',
    },
  ];

  const userTypesData = [
    {
      id: 1,
      name: 'student',
    },
    {
      id: 2,
      name: 'teacher',
    },
    {
      id: 3,
      name: 'staff',
    },
    {
      id: 4,
      name: 'parent',
    },
  ];

  const userData = [
    {
      id: 1,
      name: 'student6',
      first_name: 'John',
      last_name: 'Smith',
      email: 'john@gmail.com',
      type_id: 1,
    },
    {
      id: 2,
      name: 'student7',
      first_name: 'Alice',
      last_name: 'Adams',
      email: 'alice@adams.com',
      type_id: 1,
    },
    {
      id: 3,
      name: 'student1',
      first_name: 'Alvin',
      last_name: 'Ardsley',
      email: 'alvin@gmail.com',
      type_id: 1,
    },
    {
      id: 4,
      name: 'student2',
      first_name: 'Jennifer',
      last_name: 'Vasquez',
      email: 'jen@gmail.com',
      type_id: 1,
    },
    {
      id: 5,
      name: 'student3',
      first_name: 'Erin',
      last_name: 'McClellan',
      email: 'erin@gmail.com',
      type_id: 1,
    },
    {
      id: 6,
      name: 'student4',
      first_name: 'Lindsay',
      last_name: 'Herzog',
      email: 'lindsay@gmail.com',
      type_id: 1,
    },
    {
      id: 7,
      name: 'student5',
      first_name: 'Samuel',
      last_name: 'Growan',
      email: 'samuel@gmail.com',
      type_id: 1,
    },
    {
      id: 8,
      name: 'teacher1',
      first_name: 'Bob',
      last_name: 'Brown',
      email: 'bob@gmail.com',
      type_id: 2,
    },
    {
      id: 9,
      name: 'teacher2',
      first_name: 'Jack',
      last_name: 'Smith',
      email: 'jack@gmail.com',
      type_id: 2,
    },
    {
      id: 10,
      name: 'teacher3',
      first_name: 'Jill',
      last_name: 'Jones',
      email: 'jill@gmail.com',
      type_id: 2,
    },
    {
      id: 11,
      name: 'teacher4',
      first_name: 'Robert',
      last_name: 'Williams',
      email: 'robert@gmail.com',
      type_id: 2,
    },
    {
      id: 12,
      name: 'teacher5',
      first_name: 'Kush',
      last_name: 'Singh',
      email: 'kush@gmail.com',
      type_id: 2,
    },
  ];

  const classData = [
    {
      id: 1,
      teacher_id: '8',
      course_id: '1',
      name: 'American Literature',
      size: '20',
      start_time: '09:00:00',
      end_time: '10:00:00',
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
    },
    {
      id: 2,
      teacher_id: '9',
      course_id: '2',
      name: 'Pre-Algebra',
      size: '30',
      start_time: '10:00:00',
      end_time: '11:00:00',
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
    },
    {
      id: 3,
      teacher_id: '10',
      course_id: '3',
      name: 'Biology 1',
      size: '15',
      start_time: '11:00:00',
      end_time: '12:00:00',
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
    },
    {
      id: 4,
      teacher_id: '11',
      course_id: '3',
      name: 'Biology 2',
      size: '15',
      start_time: '09:00:00',
      end_time: '10:30:00',
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
    },
    {
      id: 5,
      teacher_id: '12',
      course_id: '4',
      name: 'Spanish',
      size: '20',
      start_time: '10:30:00',
      end_time: '12:00:00',
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
    },
  ];

  const calendarData = [{ id: 1,
    day_count: 1,
    week_day: 'Monday',
    month: 'January',
    day_of_month: 2,
    month_count: 1 },
  { id: 2,
    day_count: 2,
    week_day: 'Tuesday',
    month: 'January',
    day_of_month: 3,
    month_count: 1 },
  { id: 3,
    day_count: 3,
    week_day: 'Wednesday',
    month: 'January',
    day_of_month: 4,
    month_count: 1 },
  { id: 4,
    day_count: 4,
    week_day: 'Thursday',
    month: 'January',
    day_of_month: 5,
    month_count: 1 },
  { id: 5,
    day_count: 5,
    week_day: 'Friday',
    month: 'January',
    day_of_month: 6,
    month_count: 1 },
  { id: 6,
    day_count: 6,
    week_day: 'Saturday',
    month: 'January',
    day_of_month: 7,
    month_count: 1 },
  { id: 7,
    day_count: 7,
    week_day: 'Sunday',
    month: 'January',
    day_of_month: 8,
    month_count: 1 },
  { id: 8,
    day_count: 8,
    week_day: 'Monday',
    month: 'January',
    day_of_month: 9,
    month_count: 1 },
  { id: 9,
    day_count: 9,
    week_day: 'Tuesday',
    month: 'January',
    day_of_month: 10,
    month_count: 1 },
  { id: 10,
    day_count: 10,
    week_day: 'Wednesday',
    month: 'January',
    day_of_month: 11,
    month_count: 1 },
  { id: 11,
    day_count: 11,
    week_day: 'Thursday',
    month: 'January',
    day_of_month: 12,
    month_count: 1 },
  { id: 12,
    day_count: 12,
    week_day: 'Friday',
    month: 'January',
    day_of_month: 13,
    month_count: 1 },
  { id: 13,
    day_count: 13,
    week_day: 'Saturday',
    month: 'January',
    day_of_month: 14,
    month_count: 1 },
  { id: 14,
    day_count: 14,
    week_day: 'Sunday',
    month: 'January',
    day_of_month: 15,
    month_count: 1 },
  { id: 15,
    day_count: 15,
    week_day: 'Monday',
    month: 'January',
    day_of_month: 16,
    month_count: 1 },
  { id: 16,
    day_count: 16,
    week_day: 'Tuesday',
    month: 'January',
    day_of_month: 17,
    month_count: 1 },
  { id: 17,
    day_count: 17,
    week_day: 'Wednesday',
    month: 'January',
    day_of_month: 18,
    month_count: 1 },
  { id: 18,
    day_count: 18,
    week_day: 'Thursday',
    month: 'January',
    day_of_month: 19,
    month_count: 1 },
  { id: 19,
    day_count: 19,
    week_day: 'Friday',
    month: 'January',
    day_of_month: 20,
    month_count: 1 },
  { id: 20,
    day_count: 20,
    week_day: 'Saturday',
    month: 'January',
    day_of_month: 21,
    month_count: 1 },
  { id: 21,
    day_count: 21,
    week_day: 'Sunday',
    month: 'January',
    day_of_month: 22,
    month_count: 1 },
  { id: 22,
    day_count: 22,
    week_day: 'Monday',
    month: 'January',
    day_of_month: 23,
    month_count: 1 },
  { id: 23,
    day_count: 23,
    week_day: 'Tuesday',
    month: 'January',
    day_of_month: 24,
    month_count: 1 },
  { id: 24,
    day_count: 24,
    week_day: 'Wednesday',
    month: 'January',
    day_of_month: 25,
    month_count: 1 },
  { id: 25,
    day_count: 25,
    week_day: 'Thursday',
    month: 'January',
    day_of_month: 26,
    month_count: 1 },
  { id: 26,
    day_count: 26,
    week_day: 'Friday',
    month: 'January',
    day_of_month: 27,
    month_count: 1 },
  { id: 27,
    day_count: 27,
    week_day: 'Saturday',
    month: 'January',
    day_of_month: 28,
    month_count: 1 },
  { id: 28,
    day_count: 28,
    week_day: 'Sunday',
    month: 'January',
    day_of_month: 29,
    month_count: 1 },
  { id: 29,
    day_count: 29,
    week_day: 'Monday',
    month: 'January',
    day_of_month: 30,
    month_count: 1 },
  { id: 30,
    day_count: 30,
    week_day: 'Tuesday',
    month: 'January',
    day_of_month: 31,
    month_count: 1 },
  { id: 31,
    day_count: 31,
    week_day: 'Wednesday',
    month: 'February',
    day_of_month: 1,
    month_count: 2 },
  { id: 32,
    day_count: 32,
    week_day: 'Thursday',
    month: 'February',
    day_of_month: 2,
    month_count: 2 },
  { id: 33,
    day_count: 33,
    week_day: 'Friday',
    month: 'February',
    day_of_month: 3,
    month_count: 2 },
  { id: 34,
    day_count: 34,
    week_day: 'Saturday',
    month: 'February',
    day_of_month: 4,
    month_count: 2 },
  { id: 35,
    day_count: 35,
    week_day: 'Sunday',
    month: 'February',
    day_of_month: 5,
    month_count: 2 },
  { id: 36,
    day_count: 36,
    week_day: 'Monday',
    month: 'February',
    day_of_month: 6,
    month_count: 2 },
  { id: 37,
    day_count: 37,
    week_day: 'Tuesday',
    month: 'February',
    day_of_month: 7,
    month_count: 2 },
  { id: 38,
    day_count: 38,
    week_day: 'Wednesday',
    month: 'February',
    day_of_month: 8,
    month_count: 2 },
  { id: 39,
    day_count: 39,
    week_day: 'Thursday',
    month: 'February',
    day_of_month: 9,
    month_count: 2 },
  { id: 40,
    day_count: 40,
    week_day: 'Friday',
    month: 'February',
    day_of_month: 10,
    month_count: 2 },
  { id: 41,
    day_count: 41,
    week_day: 'Saturday',
    month: 'February',
    day_of_month: 11,
    month_count: 2 },
  { id: 42,
    day_count: 42,
    week_day: 'Sunday',
    month: 'February',
    day_of_month: 12,
    month_count: 2 },
  { id: 43,
    day_count: 43,
    week_day: 'Monday',
    month: 'February',
    day_of_month: 13,
    month_count: 2 },
  { id: 44,
    day_count: 44,
    week_day: 'Tuesday',
    month: 'February',
    day_of_month: 14,
    month_count: 2 },
  { id: 45,
    day_count: 45,
    week_day: 'Wednesday',
    month: 'February',
    day_of_month: 15,
    month_count: 2 },
  { id: 46,
    day_count: 46,
    week_day: 'Thursday',
    month: 'February',
    day_of_month: 16,
    month_count: 2 },
  { id: 47,
    day_count: 47,
    week_day: 'Friday',
    month: 'February',
    day_of_month: 17,
    month_count: 2 },
  { id: 48,
    day_count: 48,
    week_day: 'Saturday',
    month: 'February',
    day_of_month: 18,
    month_count: 2 },
  { id: 49,
    day_count: 49,
    week_day: 'Sunday',
    month: 'February',
    day_of_month: 19,
    month_count: 2 },
  { id: 50,
    day_count: 50,
    week_day: 'Monday',
    month: 'February',
    day_of_month: 20,
    month_count: 2 },
  { id: 51,
    day_count: 51,
    week_day: 'Tuesday',
    month: 'February',
    day_of_month: 21,
    month_count: 2 },
  { id: 52,
    day_count: 52,
    week_day: 'Wednesday',
    month: 'February',
    day_of_month: 22,
    month_count: 2 },
  { id: 53,
    day_count: 53,
    week_day: 'Thursday',
    month: 'February',
    day_of_month: 23,
    month_count: 2 },
  { id: 54,
    day_count: 54,
    week_day: 'Friday',
    month: 'February',
    day_of_month: 24,
    month_count: 2 },
  { id: 55,
    day_count: 55,
    week_day: 'Saturday',
    month: 'February',
    day_of_month: 25,
    month_count: 2 },
  { id: 56,
    day_count: 56,
    week_day: 'Sunday',
    month: 'February',
    day_of_month: 26,
    month_count: 2 },
  { id: 57,
    day_count: 57,
    week_day: 'Monday',
    month: 'February',
    day_of_month: 27,
    month_count: 2 },
  { id: 58,
    day_count: 58,
    week_day: 'Tuesday',
    month: 'February',
    day_of_month: 28,
    month_count: 2 },
  { id: 59,
    day_count: 59,
    week_day: 'Wednesday',
    month: 'March',
    day_of_month: 1,
    month_count: 3 },
  { id: 60,
    day_count: 60,
    week_day: 'Thursday',
    month: 'March',
    day_of_month: 2,
    month_count: 3 },
  { id: 61,
    day_count: 61,
    week_day: 'Friday',
    month: 'March',
    day_of_month: 3,
    month_count: 3 },
  { id: 62,
    day_count: 62,
    week_day: 'Saturday',
    month: 'March',
    day_of_month: 4,
    month_count: 3 },
  { id: 63,
    day_count: 63,
    week_day: 'Sunday',
    month: 'March',
    day_of_month: 5,
    month_count: 3 },
  { id: 64,
    day_count: 64,
    week_day: 'Monday',
    month: 'March',
    day_of_month: 6,
    month_count: 3 },
  { id: 65,
    day_count: 65,
    week_day: 'Tuesday',
    month: 'March',
    day_of_month: 7,
    month_count: 3 },
  { id: 66,
    day_count: 66,
    week_day: 'Wednesday',
    month: 'March',
    day_of_month: 8,
    month_count: 3 },
  { id: 67,
    day_count: 67,
    week_day: 'Thursday',
    month: 'March',
    day_of_month: 9,
    month_count: 3 },
  { id: 68,
    day_count: 68,
    week_day: 'Friday',
    month: 'March',
    day_of_month: 10,
    month_count: 3 },
  { id: 69,
    day_count: 69,
    week_day: 'Saturday',
    month: 'March',
    day_of_month: 11,
    month_count: 3 },
  { id: 70,
    day_count: 70,
    week_day: 'Sunday',
    month: 'March',
    day_of_month: 12,
    month_count: 3 },
  { id: 71,
    day_count: 71,
    week_day: 'Monday',
    month: 'March',
    day_of_month: 13,
    month_count: 3 },
  { id: 72,
    day_count: 72,
    week_day: 'Tuesday',
    month: 'March',
    day_of_month: 14,
    month_count: 3 },
  { id: 73,
    day_count: 73,
    week_day: 'Wednesday',
    month: 'March',
    day_of_month: 15,
    month_count: 3 },
  { id: 74,
    day_count: 74,
    week_day: 'Thursday',
    month: 'March',
    day_of_month: 16,
    month_count: 3 },
  { id: 75,
    day_count: 75,
    week_day: 'Friday',
    month: 'March',
    day_of_month: 17,
    month_count: 3 },
  { id: 76,
    day_count: 76,
    week_day: 'Saturday',
    month: 'March',
    day_of_month: 18,
    month_count: 3 },
  { id: 77,
    day_count: 77,
    week_day: 'Sunday',
    month: 'March',
    day_of_month: 19,
    month_count: 3 },
  { id: 78,
    day_count: 78,
    week_day: 'Monday',
    month: 'March',
    day_of_month: 20,
    month_count: 3 },
  { id: 79,
    day_count: 79,
    week_day: 'Tuesday',
    month: 'March',
    day_of_month: 21,
    month_count: 3 },
  { id: 80,
    day_count: 80,
    week_day: 'Wednesday',
    month: 'March',
    day_of_month: 22,
    month_count: 3 },
  { id: 81,
    day_count: 81,
    week_day: 'Thursday',
    month: 'March',
    day_of_month: 23,
    month_count: 3 },
  { id: 82,
    day_count: 82,
    week_day: 'Friday',
    month: 'March',
    day_of_month: 24,
    month_count: 3 },
  { id: 83,
    day_count: 83,
    week_day: 'Saturday',
    month: 'March',
    day_of_month: 25,
    month_count: 3 },
  { id: 84,
    day_count: 84,
    week_day: 'Sunday',
    month: 'March',
    day_of_month: 26,
    month_count: 3 },
  { id: 85,
    day_count: 85,
    week_day: 'Monday',
    month: 'March',
    day_of_month: 27,
    month_count: 3 },
  { id: 86,
    day_count: 86,
    week_day: 'Tuesday',
    month: 'March',
    day_of_month: 28,
    month_count: 3 },
  { id: 87,
    day_count: 87,
    week_day: 'Wednesday',
    month: 'March',
    day_of_month: 29,
    month_count: 3 },
  { id: 88,
    day_count: 88,
    week_day: 'Thursday',
    month: 'March',
    day_of_month: 30,
    month_count: 3 },
  { id: 89,
    day_count: 89,
    week_day: 'Friday',
    month: 'March',
    day_of_month: 31,
    month_count: 3 },
  { id: 90,
    day_count: 90,
    week_day: 'Saturday',
    month: 'April',
    day_of_month: 1,
    month_count: 4 },
  { id: 91,
    day_count: 91,
    week_day: 'Sunday',
    month: 'April',
    day_of_month: 2,
    month_count: 4 },
  { id: 92,
    day_count: 92,
    week_day: 'Monday',
    month: 'April',
    day_of_month: 3,
    month_count: 4 },
  { id: 93,
    day_count: 93,
    week_day: 'Tuesday',
    month: 'April',
    day_of_month: 4,
    month_count: 4 },
  { id: 94,
    day_count: 94,
    week_day: 'Wednesday',
    month: 'April',
    day_of_month: 5,
    month_count: 4 },
  { id: 95,
    day_count: 95,
    week_day: 'Thursday',
    month: 'April',
    day_of_month: 6,
    month_count: 4 },
  { id: 96,
    day_count: 96,
    week_day: 'Friday',
    month: 'April',
    day_of_month: 7,
    month_count: 4 },
  { id: 97,
    day_count: 97,
    week_day: 'Saturday',
    month: 'April',
    day_of_month: 8,
    month_count: 4 },
  { id: 98,
    day_count: 98,
    week_day: 'Sunday',
    month: 'April',
    day_of_month: 9,
    month_count: 4 },
  { id: 99,
    day_count: 99,
    week_day: 'Monday',
    month: 'April',
    day_of_month: 10,
    month_count: 4 },
  { id: 100,
    day_count: 100,
    week_day: 'Tuesday',
    month: 'April',
    day_of_month: 11,
    month_count: 4 },
  { id: 101,
    day_count: 101,
    week_day: 'Wednesday',
    month: 'April',
    day_of_month: 12,
    month_count: 4 },
  { id: 102,
    day_count: 102,
    week_day: 'Thursday',
    month: 'April',
    day_of_month: 13,
    month_count: 4 },
  { id: 103,
    day_count: 103,
    week_day: 'Friday',
    month: 'April',
    day_of_month: 14,
    month_count: 4 },
  { id: 104,
    day_count: 104,
    week_day: 'Saturday',
    month: 'April',
    day_of_month: 15,
    month_count: 4 },
  { id: 105,
    day_count: 105,
    week_day: 'Sunday',
    month: 'April',
    day_of_month: 16,
    month_count: 4 },
  { id: 106,
    day_count: 106,
    week_day: 'Monday',
    month: 'April',
    day_of_month: 17,
    month_count: 4 },
  { id: 107,
    day_count: 107,
    week_day: 'Tuesday',
    month: 'April',
    day_of_month: 18,
    month_count: 4 },
  { id: 108,
    day_count: 108,
    week_day: 'Wednesday',
    month: 'April',
    day_of_month: 19,
    month_count: 4 },
  { id: 109,
    day_count: 109,
    week_day: 'Thursday',
    month: 'April',
    day_of_month: 20,
    month_count: 4 },
  { id: 110,
    day_count: 110,
    week_day: 'Friday',
    month: 'April',
    day_of_month: 21,
    month_count: 4 },
  { id: 111,
    day_count: 111,
    week_day: 'Saturday',
    month: 'April',
    day_of_month: 22,
    month_count: 4 },
  { id: 112,
    day_count: 112,
    week_day: 'Sunday',
    month: 'April',
    day_of_month: 23,
    month_count: 4 },
  { id: 113,
    day_count: 113,
    week_day: 'Monday',
    month: 'April',
    day_of_month: 24,
    month_count: 4 },
  { id: 114,
    day_count: 114,
    week_day: 'Tuesday',
    month: 'April',
    day_of_month: 25,
    month_count: 4 },
  { id: 115,
    day_count: 115,
    week_day: 'Wednesday',
    month: 'April',
    day_of_month: 26,
    month_count: 4 },
  { id: 116,
    day_count: 116,
    week_day: 'Thursday',
    month: 'April',
    day_of_month: 27,
    month_count: 4 },
  { id: 117,
    day_count: 117,
    week_day: 'Friday',
    month: 'April',
    day_of_month: 28,
    month_count: 4 },
  { id: 118,
    day_count: 118,
    week_day: 'Saturday',
    month: 'April',
    day_of_month: 29,
    month_count: 4 },
  { id: 119,
    day_count: 119,
    week_day: 'Sunday',
    month: 'April',
    day_of_month: 30,
    month_count: 4 },
  { id: 120,
    day_count: 120,
    week_day: 'Monday',
    month: 'May',
    day_of_month: 1,
    month_count: 5 },
  { id: 121,
    day_count: 121,
    week_day: 'Tuesday',
    month: 'May',
    day_of_month: 2,
    month_count: 5 },
  { id: 122,
    day_count: 122,
    week_day: 'Wednesday',
    month: 'May',
    day_of_month: 3,
    month_count: 5 },
  { id: 123,
    day_count: 123,
    week_day: 'Thursday',
    month: 'May',
    day_of_month: 4,
    month_count: 5 },
  { id: 124,
    day_count: 124,
    week_day: 'Friday',
    month: 'May',
    day_of_month: 5,
    month_count: 5 },
  { id: 125,
    day_count: 125,
    week_day: 'Saturday',
    month: 'May',
    day_of_month: 6,
    month_count: 5 },
  { id: 126,
    day_count: 126,
    week_day: 'Sunday',
    month: 'May',
    day_of_month: 7,
    month_count: 5 },
  { id: 127,
    day_count: 127,
    week_day: 'Monday',
    month: 'May',
    day_of_month: 8,
    month_count: 5 },
  { id: 128,
    day_count: 128,
    week_day: 'Tuesday',
    month: 'May',
    day_of_month: 9,
    month_count: 5 },
  { id: 129,
    day_count: 129,
    week_day: 'Wednesday',
    month: 'May',
    day_of_month: 10,
    month_count: 5 },
  { id: 130,
    day_count: 130,
    week_day: 'Thursday',
    month: 'May',
    day_of_month: 11,
    month_count: 5 },
  { id: 131,
    day_count: 131,
    week_day: 'Friday',
    month: 'May',
    day_of_month: 12,
    month_count: 5 },
  { id: 132,
    day_count: 132,
    week_day: 'Saturday',
    month: 'May',
    day_of_month: 13,
    month_count: 5 },
  { id: 133,
    day_count: 133,
    week_day: 'Sunday',
    month: 'May',
    day_of_month: 14,
    month_count: 5 },
  { id: 134,
    day_count: 134,
    week_day: 'Monday',
    month: 'May',
    day_of_month: 15,
    month_count: 5 },
  { id: 135,
    day_count: 135,
    week_day: 'Tuesday',
    month: 'May',
    day_of_month: 16,
    month_count: 5 },
  { id: 136,
    day_count: 136,
    week_day: 'Wednesday',
    month: 'May',
    day_of_month: 17,
    month_count: 5 },
  { id: 137,
    day_count: 137,
    week_day: 'Thursday',
    month: 'May',
    day_of_month: 18,
    month_count: 5 },
  { id: 138,
    day_count: 138,
    week_day: 'Friday',
    month: 'May',
    day_of_month: 19,
    month_count: 5 },
  { id: 139,
    day_count: 139,
    week_day: 'Saturday',
    month: 'May',
    day_of_month: 20,
    month_count: 5 },
  { id: 140,
    day_count: 140,
    week_day: 'Sunday',
    month: 'May',
    day_of_month: 21,
    month_count: 5 },
  { id: 141,
    day_count: 141,
    week_day: 'Monday',
    month: 'May',
    day_of_month: 22,
    month_count: 5 },
  { id: 142,
    day_count: 142,
    week_day: 'Tuesday',
    month: 'May',
    day_of_month: 23,
    month_count: 5 },
  { id: 143,
    day_count: 143,
    week_day: 'Wednesday',
    month: 'May',
    day_of_month: 24,
    month_count: 5 },
  { id: 144,
    day_count: 144,
    week_day: 'Thursday',
    month: 'May',
    day_of_month: 25,
    month_count: 5 },
  { id: 145,
    day_count: 145,
    week_day: 'Friday',
    month: 'May',
    day_of_month: 26,
    month_count: 5 },
  { id: 146,
    day_count: 146,
    week_day: 'Saturday',
    month: 'May',
    day_of_month: 27,
    month_count: 5 },
  { id: 147,
    day_count: 147,
    week_day: 'Sunday',
    month: 'May',
    day_of_month: 28,
    month_count: 5 },
  { id: 148,
    day_count: 148,
    week_day: 'Monday',
    month: 'May',
    day_of_month: 29,
    month_count: 5 },
  { id: 149,
    day_count: 149,
    week_day: 'Tuesday',
    month: 'May',
    day_of_month: 30,
    month_count: 5 },
  { id: 150,
    day_count: 150,
    week_day: 'Wednesday',
    month: 'May',
    day_of_month: 31,
    month_count: 5 },
  { id: 151,
    day_count: 151,
    week_day: 'Thursday',
    month: 'June',
    day_of_month: 1,
    month_count: 6 },
  { id: 152,
    day_count: 152,
    week_day: 'Friday',
    month: 'June',
    day_of_month: 2,
    month_count: 6 },
  { id: 153,
    day_count: 153,
    week_day: 'Saturday',
    month: 'June',
    day_of_month: 3,
    month_count: 6 },
  { id: 154,
    day_count: 154,
    week_day: 'Sunday',
    month: 'June',
    day_of_month: 4,
    month_count: 6 },
  { id: 155,
    day_count: 155,
    week_day: 'Monday',
    month: 'June',
    day_of_month: 5,
    month_count: 6 },
  { id: 156,
    day_count: 156,
    week_day: 'Tuesday',
    month: 'June',
    day_of_month: 6,
    month_count: 6 },
  { id: 157,
    day_count: 157,
    week_day: 'Wednesday',
    month: 'June',
    day_of_month: 7,
    month_count: 6 },
  { id: 158,
    day_count: 158,
    week_day: 'Thursday',
    month: 'June',
    day_of_month: 8,
    month_count: 6 },
  { id: 159,
    day_count: 159,
    week_day: 'Friday',
    month: 'June',
    day_of_month: 9,
    month_count: 6 },
  { id: 160,
    day_count: 160,
    week_day: 'Saturday',
    month: 'June',
    day_of_month: 10,
    month_count: 6 },
  { id: 161,
    day_count: 161,
    week_day: 'Sunday',
    month: 'June',
    day_of_month: 11,
    month_count: 6 },
  { id: 162,
    day_count: 162,
    week_day: 'Monday',
    month: 'June',
    day_of_month: 12,
    month_count: 6 },
  { id: 163,
    day_count: 163,
    week_day: 'Tuesday',
    month: 'June',
    day_of_month: 13,
    month_count: 6 },
  { id: 164,
    day_count: 164,
    week_day: 'Wednesday',
    month: 'June',
    day_of_month: 14,
    month_count: 6 },
  { id: 165,
    day_count: 165,
    week_day: 'Thursday',
    month: 'June',
    day_of_month: 15,
    month_count: 6 },
  { id: 166,
    day_count: 166,
    week_day: 'Friday',
    month: 'June',
    day_of_month: 16,
    month_count: 6 },
  { id: 167,
    day_count: 167,
    week_day: 'Saturday',
    month: 'June',
    day_of_month: 17,
    month_count: 6 },
  { id: 168,
    day_count: 168,
    week_day: 'Sunday',
    month: 'June',
    day_of_month: 18,
    month_count: 6 },
  { id: 169,
    day_count: 169,
    week_day: 'Monday',
    month: 'June',
    day_of_month: 19,
    month_count: 6 },
  { id: 170,
    day_count: 170,
    week_day: 'Tuesday',
    month: 'June',
    day_of_month: 20,
    month_count: 6 },
  { id: 171,
    day_count: 171,
    week_day: 'Wednesday',
    month: 'June',
    day_of_month: 21,
    month_count: 6 },
  { id: 172,
    day_count: 172,
    week_day: 'Thursday',
    month: 'June',
    day_of_month: 22,
    month_count: 6 },
  { id: 173,
    day_count: 173,
    week_day: 'Friday',
    month: 'June',
    day_of_month: 23,
    month_count: 6 },
  { id: 174,
    day_count: 174,
    week_day: 'Saturday',
    month: 'June',
    day_of_month: 24,
    month_count: 6 },
  { id: 175,
    day_count: 175,
    week_day: 'Sunday',
    month: 'June',
    day_of_month: 25,
    month_count: 6 },
  { id: 176,
    day_count: 176,
    week_day: 'Monday',
    month: 'June',
    day_of_month: 26,
    month_count: 6 },
  { id: 177,
    day_count: 177,
    week_day: 'Tuesday',
    month: 'June',
    day_of_month: 27,
    month_count: 6 }];

  const moduleData = [
    {
      id: 1,
      module_name: 'Pre-Columbian',
      percent_of_class_grade: '.25',
      class_id: '1',
    },
    {
      id: 2,
      module_name: 'Early American',
      percent_of_class_grade: '.25',
      class_id: '1',
    },
    {
      id: 3,
      module_name: 'Industrial Revolution',
      percent_of_class_grade: '.25',
      class_id: '1',
    },
    {
      id: 4,
      module_name: '20th Century',
      percent_of_class_grade: '.25',
      class_id: '1',
    },
    {
      id: 5,
      module_name: 'Trigonometry',
      percent_of_class_grade: '.25',
      class_id: '2',
    },
    {
      id: 6,
      module_name: 'Geometry',
      percent_of_class_grade: '.25',
      class_id: '2',
    },
    {
      id: 7,
      module_name: 'Algebra',
      percent_of_class_grade: '.25',
      class_id: '2',
    },
    {
      id: 8,
      module_name: 'Statistics',
      percent_of_class_grade: '.25',
      class_id: '2',
    },
    {
      id: 9,
      module_name: 'Scientific Method',
      percent_of_class_grade: '.25',
      class_id: '3',
    },
    {
      id: 10,
      module_name: 'Characteristics of Life',
      percent_of_class_grade: '.25',
      class_id: '3',
    },
    {
      id: 11,
      module_name: 'Cells and Cell Processes',
      percent_of_class_grade: '.25',
      class_id: '3',
    },
    {
      id: 12,
      module_name: 'Genetics and DNA',
      percent_of_class_grade: '.25',
      class_id: '3',
    },
    {
      id: 13,
      module_name: 'Scientific Method',
      percent_of_class_grade: '.25',
      class_id: '4',
    },
    {
      id: 14,
      module_name: 'Characteristics of Life',
      percent_of_class_grade: '.25',
      class_id: '4',
    },
    {
      id: 15,
      module_name: 'Cells and Cell Processes',
      percent_of_class_grade: '.25',
      class_id: '4',
    },
    {
      id: 16,
      module_name: 'Genetics and DNA',
      percent_of_class_grade: '.25',
      class_id: '4',
    },
    {
      id: 17,
      module_name: 'Beginning',
      percent_of_class_grade: '.25',
      class_id: '5',
    },
    {
      id: 18,
      module_name: 'Intermediate',
      percent_of_class_grade: '.25',
      class_id: '5',
    },
    {
      id: 19,
      module_name: 'Advanced',
      percent_of_class_grade: '.25',
      class_id: '5',
    },
    {
      id: 20,
      module_name: 'Expert',
      percent_of_class_grade: '.25',
      class_id: '5',
    },
  ];

  const studentClassData = [{ student_id: 1, class_id: 1 },
  { student_id: 2, class_id: 1 },
  { student_id: 3, class_id: 1 },
  { student_id: 4, class_id: 1 },
  { student_id: 5, class_id: 1 },
  { student_id: 6, class_id: 1 },
  { student_id: 7, class_id: 1 },
  { student_id: 1, class_id: 2 },
  { student_id: 2, class_id: 2 },
  { student_id: 3, class_id: 2 },
  { student_id: 4, class_id: 2 },
  { student_id: 5, class_id: 2 },
  { student_id: 6, class_id: 2 },
  { student_id: 7, class_id: 2 },
  { student_id: 1, class_id: 3 },
  { student_id: 2, class_id: 3 },
  { student_id: 3, class_id: 3 },
  { student_id: 4, class_id: 3 },
  { student_id: 5, class_id: 4 },
  { student_id: 6, class_id: 4 },
  { student_id: 7, class_id: 4 },
  { student_id: 1, class_id: 5 },
  { student_id: 2, class_id: 5 },
  { student_id: 3, class_id: 5 },
  { student_id: 4, class_id: 5 },
  { student_id: 5, class_id: 5 },
  { student_id: 6, class_id: 5 },
  { student_id: 7, class_id: 5 }];

  const gradeableObjectTypesData = [
    {
      id: 1,
      name: 'exam',
    },
    {
      id: 2,
      name: 'quiz',
    },
    {
      id: 3,
      name: 'homework',
    },
    {
      id: 4,
      name: 'essay',
    },
    {
      id: 5,
      name: 'presentation',
    },
  ];

  const meetingsArray = [];
  const gradeableobjectArray = [];
  const attendanceArray = [];
  const graphArray = [];
  let meetingCount = 1;
  let attendanceCount = 1;
  let graphCount = 1;
  classData.forEach((classItem) => {
    calendarData.forEach((calendarDay) => {
      if (calendarDay.week_day === 'Tuesday' || calendarDay.week_day === 'Thursday') {
        meetingsArray.push({
          id: meetingCount,
          calendar_day: calendarDay.id,
          start_time: classItem.start_time,
          end_time: classItem.end_time,
          class_id: classItem.id,
        });
        gradeableobjectArray.push({
          id: meetingCount,
          object_name: `${gradeableObjectTypesData[meetingCount % 4].name} + ${meetingCount}`,
          type_id: gradeableObjectTypesData[meetingCount % 4].id,
          module_id: (classItem.id * 4) - Math.round(Math.random() * 3),
          meeting_id: meetingCount,
        });
        meetingCount += 1;
      } else if ((calendarDay.week_day === 'Monday' && classItem.monday) || (calendarDay.week_day === 'Wednesday' && classItem.wednesday) || (calendarDay.week_day === 'Friday' && classItem.friday)) {
        meetingsArray.push({
          id: meetingCount,
          calendar_day: calendarDay.id,
          start_time: classItem.start_time,
          end_time: classItem.end_time,
          class_id: classItem.id,
        });
        gradeableobjectArray.push({
          id: meetingCount,
          object_name: `${gradeableObjectTypesData[meetingCount % 4].name} ${meetingCount}`,
          type_id: gradeableObjectTypesData[meetingCount % 4].id,
          module_id: (classItem.id * 4) - Math.round(Math.random() * 3),
          meeting_id: meetingCount,
        });
        meetingCount += 1;
      }
    });
  });

  userData.forEach((user) => {
    if (user.type_id === 1) {
      studentClassData.forEach((studentClass) => {
        if (user.id === studentClass.student_id) {
          meetingsArray.forEach((meeting) => {
            if (meeting.class_id === studentClass.class_id) {
              attendanceArray.push({
                id: attendanceCount,
                meeting_id: meeting.id,
                student_id: user.id,
                present: Math.round(0.3 + (Math.random() * 0.8)),
              });
              attendanceCount += 1;
            }
          });
        }
      });
    }
  });

  // for (let i = 0; i < gradeableobjectArray.length; i += 1) {
  //   userData.forEach((user) => {
  //     if (user.type_id === 1) {
  //       graphArray.push({
  //         id: graphCount,
  //         department_id: null,
  //         course_id: null,
  //         class_id: null,
  //         teacher_id: null,
  //         student_id: attendanceArray[i].student_id,
  //         module_id: null,
  //         gradeableobject_id: attendanceArray[i].id,
  //         gradeableobjecttype_id: null,
  //         meeting_id: null,
  //         grade: (65 + Math.round(Math.random() * 35)),
  //       });
  //       graphCount += 1;
  //     }
  //   });
  // }

  gradeableobjectArray.forEach((gradeableobject) => {
    if (gradeableobject.module_id <= 4) {
      userData.forEach((user) => {
        if (user.type_id === 1) {
          graphArray.push({
            id: graphCount,
            class_id: 1,
            teacher_id: 8,
            student_id: user.id,
            module_id: gradeableobject.module_id,
            gradeableobject_id: gradeableobject.id,
            gradeableobjecttype_id: gradeableobject.type_id,
            meeting_id: gradeableobject.id,
            grade: (65 + Math.round(Math.random() * 35)),
          });
          graphCount += 1;
        }
      });
    } else if (gradeableobject.module_id <= 8) {
      userData.forEach((user) => {
        if (user.type_id === 1) {
          graphArray.push({
            id: graphCount,
            class_id: 2,
            teacher_id: 9,
            student_id: user.id,
            module_id: gradeableobject.module_id,
            gradeableobject_id: gradeableobject.id,
            gradeableobjecttype_id: gradeableobject.type_id,
            meeting_id: gradeableobject.id,
            grade: (65 + Math.round(Math.random() * 35)),
          });
          graphCount += 1;
        }
      });
    } else if (gradeableobject.module_id <= 12) {
      userData.forEach((user) => {
        if (user.type_id === 1) {
          graphArray.push({
            id: graphCount,
            class_id: 3,
            teacher_id: 10,
            student_id: user.id,
            module_id: gradeableobject.module_id,
            gradeableobject_id: gradeableobject.id,
            gradeableobjecttype_id: gradeableobject.type_id,
            meeting_id: gradeableobject.id,
            grade: (65 + Math.round(Math.random() * 35)),
          });
          graphCount += 1;
        }
      });
    } else if (gradeableobject.module_id <= 16) {
      userData.forEach((user) => {
        if (user.type_id === 1) {
          graphArray.push({
            id: graphCount,
            class_id: 4,
            teacher_id: 11,
            student_id: user.id,
            module_id: gradeableobject.module_id,
            gradeableobject_id: gradeableobject.id,
            gradeableobjecttype_id: gradeableobject.type_id,
            meeting_id: gradeableobject.id,
            grade: (65 + Math.round(Math.random() * 35)),
          });
          graphCount += 1;
        }
      });
    } else {
      userData.forEach((user) => {
        if (user.type_id === 1) {
          graphArray.push({
            id: graphCount,
            class_id: 5,
            teacher_id: 12,
            student_id: user.id,
            module_id: gradeableobject.module_id,
            gradeableobject_id: gradeableobject.id,
            gradeableobjecttype_id: gradeableobject.type_id,
            meeting_id: gradeableobject.id,
            grade: (65 + Math.round(Math.random() * 35)),
          });
          graphCount += 1;
        }
      });
    }
  });

  graphArray.forEach((graphItem) => {
    classData.forEach((classItem) => {
      if (graphItem.class_id === classItem.id) {
        graphItem.course_id = classItem.course_id;
        graphItem.department_id = classItem.course_id;
      }
    });
  });

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => Promise.all(tableData.map(table => knex(table).del())))
    .then(() => Promise.all(departmentData.map(departments =>
      knex(departmentsTable).insert(departments))))
    .then(() => Promise.all(courseData.map(courses => knex(coursesTable).insert(courses))))
    .then(() => Promise.all(
      userTypesData.map(userTypes => knex(userTypesTable).insert(userTypes))))
    .then(() => Promise.all(userData.map(user => knex(usersTable).insert(user))))
    .then(() => Promise.all(classData.map(classItem => knex(classesTable).insert(classItem))))
    .then(() => Promise.all(
      calendarData.map(calendarDay => knex(calendarTable).insert(calendarDay))))
    .then(() => Promise.all(meetingsArray.map(meeting => knex(meetingsTable).insert(meeting))))
    .then(() => Promise.all(moduleData.map(classModule => knex(modulesTable).insert(classModule))))
    .then(() =>
    Promise.all(studentClassData.map(studentClass => knex(studentClassTable).insert(studentClass))))
    .then(() =>
    Promise.all(gradeableObjectTypesData.map(gradeableobjectType =>
      knex(gradeableObjectTypesTable).insert(gradeableobjectType))))
    .then(() => Promise.all(gradeableobjectArray.map(gradeableobject =>
      knex(gradeableObjectsTable).insert(gradeableobject))))
    .then(() => Promise.all(attendanceArray.map(attendance =>
      knex(attendanceTable).insert(attendance))))
    .then(() => Promise.all(graphArray.map(grade =>
      knex(graphTable).insert(grade))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
