exports.seed = (knex, Promise) => {
  const tableName = 'gradeable_objects';
  const data = [
    {
      id: 1,
      object_name: 'Homework - Short Essay',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '.2',
      module_id: '1',
      type_id: '3',
    },
    {
      id: 2,
      object_name: 'Homework - Long Essay',
      duration: '3',
      file_id: '0',
      percent_of_module_grade: '.4',
      module_id: '1',
      type_id: '4',
    },
    {
      id: 3,
      object_name: 'Homework - Worksheet',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '.2',
      module_id: '1',
      type_id: '3',
    },
    {
      id: 4,
      object_name: 'Homework - Short Response',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '.2',
      module_id: '1',
      type_id: '3',
    },
    {
      id: 5,
      object_name: 'Final Exam',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 6,
      object_name: 'GradeObj 6',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 7,
      object_name: 'GradeObj 7',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 8,
      object_name: 'GradeObj 8',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 9,
      object_name: 'GradeObj 9',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 10,
      object_name: 'GradeObj 10',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 11,
      object_name: 'GradeObj 11',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 12,
      object_name: 'GradeObj 12',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 13,
      object_name: 'GradeObj 13',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
    {
      id: 14,
      object_name: 'GradeObj 14',
      duration: '1',
      file_id: '0',
      percent_of_module_grade: '1',
      module_id: '4',
      type_id: '1',
    },
  ];

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => knex(tableName).del())
    .then(() => Promise.all(data.map(type => knex(tableName).insert(type))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
