exports.seed = (knex, Promise) => {
  const tableName = 'gradeable_objects';
  const data = [{ id: 1,
    object_name: 'Homework 1',
    day_assigned: 1,
    day_due: 1,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 2,
    object_name: 'Homework 2',
    day_assigned: 1,
    day_due: 1,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 3,
    object_name: 'Homework 3',
    day_assigned: 1,
    day_due: 1,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 4,
    object_name: 'Homework 4',
    day_assigned: 2,
    day_due: 2,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 5,
    object_name: 'Homework 5',
    day_assigned: 2,
    day_due: 2,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 6,
    object_name: 'Homework 6',
    day_assigned: 3,
    day_due: 3,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 7,
    object_name: 'Homework 7',
    day_assigned: 3,
    day_due: 3,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 8,
    object_name: 'Homework 8',
    day_assigned: 3,
    day_due: 3,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 9,
    object_name: 'Homework 9',
    day_assigned: 4,
    day_due: 4,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 10,
    object_name: 'Homework 10',
    day_assigned: 4,
    day_due: 4,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 11,
    object_name: 'Homework 11',
    day_assigned: 5,
    day_due: 5,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 12,
    object_name: 'Homework 12',
    day_assigned: 5,
    day_due: 5,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 13,
    object_name: 'Homework 13',
    day_assigned: 5,
    day_due: 5,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 14,
    object_name: 'Homework 14',
    day_assigned: 6,
    day_due: 6,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 15,
    object_name: 'Homework 15',
    day_assigned: 6,
    day_due: 6,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 16,
    object_name: 'Homework 16',
    day_assigned: 7,
    day_due: 7,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 17,
    object_name: 'Homework 17',
    day_assigned: 7,
    day_due: 7,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 18,
    object_name: 'Homework 18',
    day_assigned: 8,
    day_due: 8,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 19,
    object_name: 'Homework 19',
    day_assigned: 8,
    day_due: 8,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 20,
    object_name: 'Homework 20',
    day_assigned: 8,
    day_due: 8,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 21,
    object_name: 'Homework 21',
    day_assigned: 9,
    day_due: 9,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 22,
    object_name: 'Homework 22',
    day_assigned: 9,
    day_due: 9,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 23,
    object_name: 'Homework 23',
    day_assigned: 10,
    day_due: 10,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 24,
    object_name: 'Homework 24',
    day_assigned: 10,
    day_due: 10,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 25,
    object_name: 'Homework 25',
    day_assigned: 10,
    day_due: 10,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 26,
    object_name: 'Homework 26',
    day_assigned: 11,
    day_due: 11,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 27,
    object_name: 'Homework 27',
    day_assigned: 11,
    day_due: 11,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 28,
    object_name: 'Homework 28',
    day_assigned: 12,
    day_due: 12,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 29,
    object_name: 'Homework 29',
    day_assigned: 12,
    day_due: 12,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 30,
    object_name: 'Homework 30',
    day_assigned: 12,
    day_due: 12,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 31,
    object_name: 'Homework 31',
    day_assigned: 13,
    day_due: 13,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 32,
    object_name: 'Homework 32',
    day_assigned: 13,
    day_due: 13,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 33,
    object_name: 'Homework 33',
    day_assigned: 14,
    day_due: 14,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 34,
    object_name: 'Homework 34',
    day_assigned: 14,
    day_due: 14,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 35,
    object_name: 'Homework 35',
    day_assigned: 15,
    day_due: 15,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 36,
    object_name: 'Homework 36',
    day_assigned: 15,
    day_due: 15,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 37,
    object_name: 'Homework 37',
    day_assigned: 15,
    day_due: 15,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 38,
    object_name: 'Homework 38',
    day_assigned: 16,
    day_due: 16,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 39,
    object_name: 'Homework 39',
    day_assigned: 16,
    day_due: 16,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 40,
    object_name: 'Homework 40',
    day_assigned: 17,
    day_due: 17,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 41,
    object_name: 'Homework 41',
    day_assigned: 17,
    day_due: 17,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 42,
    object_name: 'Homework 42',
    day_assigned: 17,
    day_due: 17,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 43,
    object_name: 'Homework 43',
    day_assigned: 18,
    day_due: 18,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 44,
    object_name: 'Homework 44',
    day_assigned: 18,
    day_due: 18,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 45,
    object_name: 'Homework 45',
    day_assigned: 19,
    day_due: 19,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 46,
    object_name: 'Homework 46',
    day_assigned: 19,
    day_due: 19,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 47,
    object_name: 'Homework 47',
    day_assigned: 19,
    day_due: 19,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 48,
    object_name: 'Homework 48',
    day_assigned: 20,
    day_due: 20,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 49,
    object_name: 'Homework 49',
    day_assigned: 20,
    day_due: 20,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 50,
    object_name: 'Homework 50',
    day_assigned: 21,
    day_due: 21,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 51,
    object_name: 'Homework 51',
    day_assigned: 21,
    day_due: 21,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 52,
    object_name: 'Homework 52',
    day_assigned: 22,
    day_due: 22,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 53,
    object_name: 'Homework 53',
    day_assigned: 22,
    day_due: 22,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 54,
    object_name: 'Homework 54',
    day_assigned: 22,
    day_due: 22,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 55,
    object_name: 'Homework 55',
    day_assigned: 23,
    day_due: 23,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 56,
    object_name: 'Homework 56',
    day_assigned: 23,
    day_due: 23,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 57,
    object_name: 'Homework 57',
    day_assigned: 24,
    day_due: 24,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 58,
    object_name: 'Homework 58',
    day_assigned: 24,
    day_due: 24,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 59,
    object_name: 'Homework 59',
    day_assigned: 24,
    day_due: 24,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 60,
    object_name: 'Homework 60',
    day_assigned: 25,
    day_due: 25,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 61,
    object_name: 'Homework 61',
    day_assigned: 25,
    day_due: 25,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 62,
    object_name: 'Homework 62',
    day_assigned: 26,
    day_due: 26,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 63,
    object_name: 'Homework 63',
    day_assigned: 26,
    day_due: 26,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 64,
    object_name: 'Homework 64',
    day_assigned: 26,
    day_due: 26,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 65,
    object_name: 'Homework 65',
    day_assigned: 27,
    day_due: 27,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 66,
    object_name: 'Homework 66',
    day_assigned: 27,
    day_due: 27,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 67,
    object_name: 'Homework 67',
    day_assigned: 28,
    day_due: 28,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 68,
    object_name: 'Homework 68',
    day_assigned: 28,
    day_due: 28,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 69,
    object_name: 'Homework 69',
    day_assigned: 29,
    day_due: 29,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 70,
    object_name: 'Homework 70',
    day_assigned: 29,
    day_due: 29,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 71,
    object_name: 'Homework 71',
    day_assigned: 29,
    day_due: 29,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 72,
    object_name: 'Homework 72',
    day_assigned: 30,
    day_due: 30,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 73,
    object_name: 'Homework 73',
    day_assigned: 30,
    day_due: 30,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 74,
    object_name: 'Homework 74',
    day_assigned: 31,
    day_due: 31,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 75,
    object_name: 'Homework 75',
    day_assigned: 31,
    day_due: 31,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 76,
    object_name: 'Homework 76',
    day_assigned: 31,
    day_due: 31,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 77,
    object_name: 'Homework 77',
    day_assigned: 32,
    day_due: 32,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 78,
    object_name: 'Homework 78',
    day_assigned: 32,
    day_due: 32,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 79,
    object_name: 'Homework 79',
    day_assigned: 33,
    day_due: 33,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 80,
    object_name: 'Homework 80',
    day_assigned: 33,
    day_due: 33,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 81,
    object_name: 'Homework 81',
    day_assigned: 33,
    day_due: 33,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 82,
    object_name: 'Homework 82',
    day_assigned: 34,
    day_due: 34,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 83,
    object_name: 'Homework 83',
    day_assigned: 34,
    day_due: 34,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 84,
    object_name: 'Homework 84',
    day_assigned: 35,
    day_due: 35,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 85,
    object_name: 'Homework 85',
    day_assigned: 35,
    day_due: 35,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 86,
    object_name: 'Homework 86',
    day_assigned: 36,
    day_due: 36,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 87,
    object_name: 'Homework 87',
    day_assigned: 36,
    day_due: 36,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 88,
    object_name: 'Homework 88',
    day_assigned: 36,
    day_due: 36,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 89,
    object_name: 'Homework 89',
    day_assigned: 37,
    day_due: 37,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 90,
    object_name: 'Homework 90',
    day_assigned: 37,
    day_due: 37,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 91,
    object_name: 'Homework 91',
    day_assigned: 38,
    day_due: 38,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 92,
    object_name: 'Homework 92',
    day_assigned: 38,
    day_due: 38,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 93,
    object_name: 'Homework 93',
    day_assigned: 38,
    day_due: 38,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 94,
    object_name: 'Homework 94',
    day_assigned: 39,
    day_due: 39,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 95,
    object_name: 'Homework 95',
    day_assigned: 39,
    day_due: 39,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 96,
    object_name: 'Homework 96',
    day_assigned: 40,
    day_due: 40,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 97,
    object_name: 'Homework 97',
    day_assigned: 40,
    day_due: 40,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 98,
    object_name: 'Homework 98',
    day_assigned: 40,
    day_due: 40,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 99,
    object_name: 'Homework 99',
    day_assigned: 41,
    day_due: 41,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 100,
    object_name: 'Homework 100',
    day_assigned: 41,
    day_due: 41,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 101,
    object_name: 'Homework 101',
    day_assigned: 42,
    day_due: 42,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 102,
    object_name: 'Homework 102',
    day_assigned: 42,
    day_due: 42,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 103,
    object_name: 'Homework 103',
    day_assigned: 43,
    day_due: 43,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 104,
    object_name: 'Homework 104',
    day_assigned: 43,
    day_due: 43,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 105,
    object_name: 'Homework 105',
    day_assigned: 43,
    day_due: 43,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 106,
    object_name: 'Homework 106',
    day_assigned: 44,
    day_due: 44,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 107,
    object_name: 'Homework 107',
    day_assigned: 44,
    day_due: 44,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 108,
    object_name: 'Homework 108',
    day_assigned: 45,
    day_due: 45,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 109,
    object_name: 'Homework 109',
    day_assigned: 45,
    day_due: 45,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 110,
    object_name: 'Homework 110',
    day_assigned: 45,
    day_due: 45,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 111,
    object_name: 'Homework 111',
    day_assigned: 46,
    day_due: 46,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 112,
    object_name: 'Homework 112',
    day_assigned: 46,
    day_due: 46,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 113,
    object_name: 'Homework 113',
    day_assigned: 47,
    day_due: 47,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 114,
    object_name: 'Homework 114',
    day_assigned: 47,
    day_due: 47,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 115,
    object_name: 'Homework 115',
    day_assigned: 47,
    day_due: 47,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 116,
    object_name: 'Homework 116',
    day_assigned: 48,
    day_due: 48,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 117,
    object_name: 'Homework 117',
    day_assigned: 48,
    day_due: 48,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 118,
    object_name: 'Homework 118',
    day_assigned: 49,
    day_due: 49,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 119,
    object_name: 'Homework 119',
    day_assigned: 49,
    day_due: 49,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 120,
    object_name: 'Homework 120',
    day_assigned: 50,
    day_due: 50,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 121,
    object_name: 'Homework 121',
    day_assigned: 50,
    day_due: 50,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 122,
    object_name: 'Homework 122',
    day_assigned: 50,
    day_due: 50,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 123,
    object_name: 'Homework 123',
    day_assigned: 51,
    day_due: 51,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 124,
    object_name: 'Homework 124',
    day_assigned: 51,
    day_due: 51,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 125,
    object_name: 'Homework 125',
    day_assigned: 52,
    day_due: 52,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 126,
    object_name: 'Homework 126',
    day_assigned: 52,
    day_due: 52,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 127,
    object_name: 'Homework 127',
    day_assigned: 52,
    day_due: 52,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 128,
    object_name: 'Homework 128',
    day_assigned: 53,
    day_due: 53,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 129,
    object_name: 'Homework 129',
    day_assigned: 53,
    day_due: 53,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 130,
    object_name: 'Homework 130',
    day_assigned: 54,
    day_due: 54,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 131,
    object_name: 'Homework 131',
    day_assigned: 54,
    day_due: 54,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 132,
    object_name: 'Homework 132',
    day_assigned: 54,
    day_due: 54,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 133,
    object_name: 'Homework 133',
    day_assigned: 55,
    day_due: 55,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 134,
    object_name: 'Homework 134',
    day_assigned: 55,
    day_due: 55,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 135,
    object_name: 'Homework 135',
    day_assigned: 56,
    day_due: 56,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 136,
    object_name: 'Homework 136',
    day_assigned: 56,
    day_due: 56,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 137,
    object_name: 'Homework 137',
    day_assigned: 57,
    day_due: 57,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 138,
    object_name: 'Homework 138',
    day_assigned: 57,
    day_due: 57,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 139,
    object_name: 'Homework 139',
    day_assigned: 57,
    day_due: 57,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 140,
    object_name: 'Homework 140',
    day_assigned: 58,
    day_due: 58,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 141,
    object_name: 'Homework 141',
    day_assigned: 58,
    day_due: 58,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 142,
    object_name: 'Homework 142',
    day_assigned: 59,
    day_due: 59,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 143,
    object_name: 'Homework 143',
    day_assigned: 59,
    day_due: 59,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 144,
    object_name: 'Homework 144',
    day_assigned: 59,
    day_due: 59,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 145,
    object_name: 'Homework 145',
    day_assigned: 60,
    day_due: 60,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 146,
    object_name: 'Homework 146',
    day_assigned: 60,
    day_due: 60,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 147,
    object_name: 'Homework 147',
    day_assigned: 61,
    day_due: 61,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 148,
    object_name: 'Homework 148',
    day_assigned: 61,
    day_due: 61,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 149,
    object_name: 'Homework 149',
    day_assigned: 61,
    day_due: 61,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 150,
    object_name: 'Homework 150',
    day_assigned: 62,
    day_due: 62,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 151,
    object_name: 'Homework 151',
    day_assigned: 62,
    day_due: 62,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 152,
    object_name: 'Homework 152',
    day_assigned: 63,
    day_due: 63,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 153,
    object_name: 'Homework 153',
    day_assigned: 63,
    day_due: 63,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 154,
    object_name: 'Homework 154',
    day_assigned: 64,
    day_due: 64,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 155,
    object_name: 'Homework 155',
    day_assigned: 64,
    day_due: 64,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 156,
    object_name: 'Homework 156',
    day_assigned: 64,
    day_due: 64,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 157,
    object_name: 'Homework 157',
    day_assigned: 65,
    day_due: 65,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 158,
    object_name: 'Homework 158',
    day_assigned: 65,
    day_due: 65,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 159,
    object_name: 'Homework 159',
    day_assigned: 66,
    day_due: 66,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 160,
    object_name: 'Homework 160',
    day_assigned: 66,
    day_due: 66,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 161,
    object_name: 'Homework 161',
    day_assigned: 66,
    day_due: 66,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 162,
    object_name: 'Homework 162',
    day_assigned: 67,
    day_due: 67,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 163,
    object_name: 'Homework 163',
    day_assigned: 67,
    day_due: 67,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 164,
    object_name: 'Homework 164',
    day_assigned: 68,
    day_due: 68,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 165,
    object_name: 'Homework 165',
    day_assigned: 68,
    day_due: 68,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 166,
    object_name: 'Homework 166',
    day_assigned: 68,
    day_due: 68,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 167,
    object_name: 'Homework 167',
    day_assigned: 69,
    day_due: 69,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 168,
    object_name: 'Homework 168',
    day_assigned: 69,
    day_due: 69,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 169,
    object_name: 'Homework 169',
    day_assigned: 70,
    day_due: 70,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 170,
    object_name: 'Homework 170',
    day_assigned: 70,
    day_due: 70,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 171,
    object_name: 'Homework 171',
    day_assigned: 71,
    day_due: 71,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 172,
    object_name: 'Homework 172',
    day_assigned: 71,
    day_due: 71,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 173,
    object_name: 'Homework 173',
    day_assigned: 71,
    day_due: 71,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 174,
    object_name: 'Homework 174',
    day_assigned: 72,
    day_due: 72,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 175,
    object_name: 'Homework 175',
    day_assigned: 72,
    day_due: 72,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 176,
    object_name: 'Homework 176',
    day_assigned: 73,
    day_due: 73,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 177,
    object_name: 'Homework 177',
    day_assigned: 73,
    day_due: 73,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 178,
    object_name: 'Homework 178',
    day_assigned: 73,
    day_due: 73,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 179,
    object_name: 'Homework 179',
    day_assigned: 74,
    day_due: 74,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 180,
    object_name: 'Homework 180',
    day_assigned: 74,
    day_due: 74,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 181,
    object_name: 'Homework 181',
    day_assigned: 75,
    day_due: 75,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 182,
    object_name: 'Homework 182',
    day_assigned: 75,
    day_due: 75,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 183,
    object_name: 'Homework 183',
    day_assigned: 75,
    day_due: 75,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 184,
    object_name: 'Homework 184',
    day_assigned: 76,
    day_due: 76,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 185,
    object_name: 'Homework 185',
    day_assigned: 76,
    day_due: 76,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 186,
    object_name: 'Homework 186',
    day_assigned: 77,
    day_due: 77,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 187,
    object_name: 'Homework 187',
    day_assigned: 77,
    day_due: 77,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 188,
    object_name: 'Homework 188',
    day_assigned: 78,
    day_due: 78,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 189,
    object_name: 'Homework 189',
    day_assigned: 78,
    day_due: 78,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 190,
    object_name: 'Homework 190',
    day_assigned: 78,
    day_due: 78,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 191,
    object_name: 'Homework 191',
    day_assigned: 79,
    day_due: 79,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 192,
    object_name: 'Homework 192',
    day_assigned: 79,
    day_due: 79,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 193,
    object_name: 'Homework 193',
    day_assigned: 80,
    day_due: 80,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 194,
    object_name: 'Homework 194',
    day_assigned: 80,
    day_due: 80,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 195,
    object_name: 'Homework 195',
    day_assigned: 80,
    day_due: 80,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 196,
    object_name: 'Homework 196',
    day_assigned: 81,
    day_due: 81,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 197,
    object_name: 'Homework 197',
    day_assigned: 81,
    day_due: 81,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 198,
    object_name: 'Homework 198',
    day_assigned: 82,
    day_due: 82,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 199,
    object_name: 'Homework 199',
    day_assigned: 82,
    day_due: 82,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 200,
    object_name: 'Homework 200',
    day_assigned: 82,
    day_due: 82,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 201,
    object_name: 'Homework 201',
    day_assigned: 83,
    day_due: 83,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 202,
    object_name: 'Homework 202',
    day_assigned: 83,
    day_due: 83,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 203,
    object_name: 'Homework 203',
    day_assigned: 84,
    day_due: 84,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 204,
    object_name: 'Homework 204',
    day_assigned: 84,
    day_due: 84,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 205,
    object_name: 'Homework 205',
    day_assigned: 85,
    day_due: 85,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 206,
    object_name: 'Homework 206',
    day_assigned: 85,
    day_due: 85,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 207,
    object_name: 'Homework 207',
    day_assigned: 85,
    day_due: 85,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 208,
    object_name: 'Homework 208',
    day_assigned: 86,
    day_due: 86,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 209,
    object_name: 'Homework 209',
    day_assigned: 86,
    day_due: 86,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 210,
    object_name: 'Homework 210',
    day_assigned: 87,
    day_due: 87,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 211,
    object_name: 'Homework 211',
    day_assigned: 87,
    day_due: 87,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 212,
    object_name: 'Homework 212',
    day_assigned: 87,
    day_due: 87,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 213,
    object_name: 'Homework 213',
    day_assigned: 88,
    day_due: 88,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 214,
    object_name: 'Homework 214',
    day_assigned: 88,
    day_due: 88,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 215,
    object_name: 'Homework 215',
    day_assigned: 89,
    day_due: 89,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 216,
    object_name: 'Homework 216',
    day_assigned: 89,
    day_due: 89,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 217,
    object_name: 'Homework 217',
    day_assigned: 89,
    day_due: 89,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 218,
    object_name: 'Homework 218',
    day_assigned: 90,
    day_due: 90,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 219,
    object_name: 'Homework 219',
    day_assigned: 90,
    day_due: 90,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 220,
    object_name: 'Homework 220',
    day_assigned: 91,
    day_due: 91,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 221,
    object_name: 'Homework 221',
    day_assigned: 91,
    day_due: 91,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 222,
    object_name: 'Homework 222',
    day_assigned: 92,
    day_due: 92,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 223,
    object_name: 'Homework 223',
    day_assigned: 92,
    day_due: 92,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 224,
    object_name: 'Homework 224',
    day_assigned: 92,
    day_due: 92,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 225,
    object_name: 'Homework 225',
    day_assigned: 93,
    day_due: 93,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 226,
    object_name: 'Homework 226',
    day_assigned: 93,
    day_due: 93,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 227,
    object_name: 'Homework 227',
    day_assigned: 94,
    day_due: 94,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 228,
    object_name: 'Homework 228',
    day_assigned: 94,
    day_due: 94,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 229,
    object_name: 'Homework 229',
    day_assigned: 94,
    day_due: 94,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 230,
    object_name: 'Homework 230',
    day_assigned: 95,
    day_due: 95,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 231,
    object_name: 'Homework 231',
    day_assigned: 95,
    day_due: 95,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 232,
    object_name: 'Homework 232',
    day_assigned: 96,
    day_due: 96,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 233,
    object_name: 'Homework 233',
    day_assigned: 96,
    day_due: 96,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 234,
    object_name: 'Homework 234',
    day_assigned: 96,
    day_due: 96,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 235,
    object_name: 'Homework 235',
    day_assigned: 97,
    day_due: 97,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 236,
    object_name: 'Homework 236',
    day_assigned: 97,
    day_due: 97,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 237,
    object_name: 'Homework 237',
    day_assigned: 98,
    day_due: 98,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 238,
    object_name: 'Homework 238',
    day_assigned: 98,
    day_due: 98,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 239,
    object_name: 'Homework 239',
    day_assigned: 99,
    day_due: 99,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 240,
    object_name: 'Homework 240',
    day_assigned: 99,
    day_due: 99,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 241,
    object_name: 'Homework 241',
    day_assigned: 99,
    day_due: 99,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 242,
    object_name: 'Homework 242',
    day_assigned: 100,
    day_due: 100,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 243,
    object_name: 'Homework 243',
    day_assigned: 100,
    day_due: 100,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 244,
    object_name: 'Homework 244',
    day_assigned: 101,
    day_due: 101,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 245,
    object_name: 'Homework 245',
    day_assigned: 101,
    day_due: 101,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 246,
    object_name: 'Homework 246',
    day_assigned: 101,
    day_due: 101,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 247,
    object_name: 'Homework 247',
    day_assigned: 102,
    day_due: 102,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 248,
    object_name: 'Homework 248',
    day_assigned: 102,
    day_due: 102,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 249,
    object_name: 'Homework 249',
    day_assigned: 103,
    day_due: 103,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 250,
    object_name: 'Homework 250',
    day_assigned: 103,
    day_due: 103,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 251,
    object_name: 'Homework 251',
    day_assigned: 103,
    day_due: 103,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 252,
    object_name: 'Homework 252',
    day_assigned: 104,
    day_due: 104,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 253,
    object_name: 'Homework 253',
    day_assigned: 104,
    day_due: 104,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 254,
    object_name: 'Homework 254',
    day_assigned: 105,
    day_due: 105,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 255,
    object_name: 'Homework 255',
    day_assigned: 105,
    day_due: 105,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 256,
    object_name: 'Homework 256',
    day_assigned: 106,
    day_due: 106,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 257,
    object_name: 'Homework 257',
    day_assigned: 106,
    day_due: 106,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 258,
    object_name: 'Homework 258',
    day_assigned: 106,
    day_due: 106,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 259,
    object_name: 'Homework 259',
    day_assigned: 107,
    day_due: 107,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 260,
    object_name: 'Homework 260',
    day_assigned: 107,
    day_due: 107,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 261,
    object_name: 'Homework 261',
    day_assigned: 108,
    day_due: 108,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 262,
    object_name: 'Homework 262',
    day_assigned: 108,
    day_due: 108,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 263,
    object_name: 'Homework 263',
    day_assigned: 108,
    day_due: 108,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 264,
    object_name: 'Homework 264',
    day_assigned: 109,
    day_due: 109,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 265,
    object_name: 'Homework 265',
    day_assigned: 109,
    day_due: 109,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 266,
    object_name: 'Homework 266',
    day_assigned: 110,
    day_due: 110,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 267,
    object_name: 'Homework 267',
    day_assigned: 110,
    day_due: 110,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 268,
    object_name: 'Homework 268',
    day_assigned: 110,
    day_due: 110,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 269,
    object_name: 'Homework 269',
    day_assigned: 111,
    day_due: 111,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 270,
    object_name: 'Homework 270',
    day_assigned: 111,
    day_due: 111,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 271,
    object_name: 'Homework 271',
    day_assigned: 112,
    day_due: 112,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 272,
    object_name: 'Homework 272',
    day_assigned: 112,
    day_due: 112,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 273,
    object_name: 'Homework 273',
    day_assigned: 113,
    day_due: 113,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 274,
    object_name: 'Homework 274',
    day_assigned: 113,
    day_due: 113,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 275,
    object_name: 'Homework 275',
    day_assigned: 113,
    day_due: 113,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 276,
    object_name: 'Homework 276',
    day_assigned: 114,
    day_due: 114,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 277,
    object_name: 'Homework 277',
    day_assigned: 114,
    day_due: 114,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 278,
    object_name: 'Homework 278',
    day_assigned: 115,
    day_due: 115,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 279,
    object_name: 'Homework 279',
    day_assigned: 115,
    day_due: 115,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 280,
    object_name: 'Homework 280',
    day_assigned: 115,
    day_due: 115,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 281,
    object_name: 'Homework 281',
    day_assigned: 116,
    day_due: 116,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 282,
    object_name: 'Homework 282',
    day_assigned: 116,
    day_due: 116,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 283,
    object_name: 'Homework 283',
    day_assigned: 117,
    day_due: 117,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 284,
    object_name: 'Homework 284',
    day_assigned: 117,
    day_due: 117,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 285,
    object_name: 'Homework 285',
    day_assigned: 117,
    day_due: 117,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 286,
    object_name: 'Homework 286',
    day_assigned: 118,
    day_due: 118,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 287,
    object_name: 'Homework 287',
    day_assigned: 118,
    day_due: 118,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 288,
    object_name: 'Homework 288',
    day_assigned: 119,
    day_due: 119,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 289,
    object_name: 'Homework 289',
    day_assigned: 119,
    day_due: 119,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 290,
    object_name: 'Homework 290',
    day_assigned: 120,
    day_due: 120,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 291,
    object_name: 'Homework 291',
    day_assigned: 120,
    day_due: 120,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 292,
    object_name: 'Homework 292',
    day_assigned: 120,
    day_due: 120,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 293,
    object_name: 'Homework 293',
    day_assigned: 121,
    day_due: 121,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 294,
    object_name: 'Homework 294',
    day_assigned: 121,
    day_due: 121,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 295,
    object_name: 'Homework 295',
    day_assigned: 122,
    day_due: 122,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 296,
    object_name: 'Homework 296',
    day_assigned: 122,
    day_due: 122,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 297,
    object_name: 'Homework 297',
    day_assigned: 122,
    day_due: 122,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 298,
    object_name: 'Homework 298',
    day_assigned: 123,
    day_due: 123,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 299,
    object_name: 'Homework 299',
    day_assigned: 123,
    day_due: 123,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 300,
    object_name: 'Homework 300',
    day_assigned: 124,
    day_due: 124,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 301,
    object_name: 'Homework 301',
    day_assigned: 124,
    day_due: 124,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 302,
    object_name: 'Homework 302',
    day_assigned: 124,
    day_due: 124,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 303,
    object_name: 'Homework 303',
    day_assigned: 125,
    day_due: 125,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 304,
    object_name: 'Homework 304',
    day_assigned: 125,
    day_due: 125,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 305,
    object_name: 'Homework 305',
    day_assigned: 126,
    day_due: 126,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 306,
    object_name: 'Homework 306',
    day_assigned: 126,
    day_due: 126,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 307,
    object_name: 'Homework 307',
    day_assigned: 127,
    day_due: 127,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 308,
    object_name: 'Homework 308',
    day_assigned: 127,
    day_due: 127,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 309,
    object_name: 'Homework 309',
    day_assigned: 127,
    day_due: 127,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 310,
    object_name: 'Homework 310',
    day_assigned: 128,
    day_due: 128,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 311,
    object_name: 'Homework 311',
    day_assigned: 128,
    day_due: 128,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 312,
    object_name: 'Homework 312',
    day_assigned: 129,
    day_due: 129,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 313,
    object_name: 'Homework 313',
    day_assigned: 129,
    day_due: 129,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 314,
    object_name: 'Homework 314',
    day_assigned: 129,
    day_due: 129,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 315,
    object_name: 'Homework 315',
    day_assigned: 130,
    day_due: 130,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 316,
    object_name: 'Homework 316',
    day_assigned: 130,
    day_due: 130,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 317,
    object_name: 'Homework 317',
    day_assigned: 131,
    day_due: 131,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 318,
    object_name: 'Homework 318',
    day_assigned: 131,
    day_due: 131,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 319,
    object_name: 'Homework 319',
    day_assigned: 131,
    day_due: 131,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 320,
    object_name: 'Homework 320',
    day_assigned: 132,
    day_due: 132,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 321,
    object_name: 'Homework 321',
    day_assigned: 132,
    day_due: 132,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 322,
    object_name: 'Homework 322',
    day_assigned: 133,
    day_due: 133,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 323,
    object_name: 'Homework 323',
    day_assigned: 133,
    day_due: 133,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 324,
    object_name: 'Homework 324',
    day_assigned: 134,
    day_due: 134,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 325,
    object_name: 'Homework 325',
    day_assigned: 134,
    day_due: 134,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 326,
    object_name: 'Homework 326',
    day_assigned: 134,
    day_due: 134,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 327,
    object_name: 'Homework 327',
    day_assigned: 135,
    day_due: 135,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 328,
    object_name: 'Homework 328',
    day_assigned: 135,
    day_due: 135,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 329,
    object_name: 'Homework 329',
    day_assigned: 136,
    day_due: 136,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 330,
    object_name: 'Homework 330',
    day_assigned: 136,
    day_due: 136,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 331,
    object_name: 'Homework 331',
    day_assigned: 136,
    day_due: 136,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 332,
    object_name: 'Homework 332',
    day_assigned: 137,
    day_due: 137,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 333,
    object_name: 'Homework 333',
    day_assigned: 137,
    day_due: 137,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 334,
    object_name: 'Homework 334',
    day_assigned: 138,
    day_due: 138,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 335,
    object_name: 'Homework 335',
    day_assigned: 138,
    day_due: 138,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 336,
    object_name: 'Homework 336',
    day_assigned: 138,
    day_due: 138,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 337,
    object_name: 'Homework 337',
    day_assigned: 139,
    day_due: 139,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 338,
    object_name: 'Homework 338',
    day_assigned: 139,
    day_due: 139,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 339,
    object_name: 'Homework 339',
    day_assigned: 140,
    day_due: 140,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 340,
    object_name: 'Homework 340',
    day_assigned: 140,
    day_due: 140,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 341,
    object_name: 'Homework 341',
    day_assigned: 141,
    day_due: 141,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 342,
    object_name: 'Homework 342',
    day_assigned: 141,
    day_due: 141,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 343,
    object_name: 'Homework 343',
    day_assigned: 141,
    day_due: 141,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 344,
    object_name: 'Homework 344',
    day_assigned: 142,
    day_due: 142,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 345,
    object_name: 'Homework 345',
    day_assigned: 142,
    day_due: 142,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 346,
    object_name: 'Homework 346',
    day_assigned: 143,
    day_due: 143,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 347,
    object_name: 'Homework 347',
    day_assigned: 143,
    day_due: 143,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 348,
    object_name: 'Homework 348',
    day_assigned: 143,
    day_due: 143,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 349,
    object_name: 'Homework 349',
    day_assigned: 144,
    day_due: 144,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 350,
    object_name: 'Homework 350',
    day_assigned: 144,
    day_due: 144,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 351,
    object_name: 'Homework 351',
    day_assigned: 145,
    day_due: 145,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 352,
    object_name: 'Homework 352',
    day_assigned: 145,
    day_due: 145,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 353,
    object_name: 'Homework 353',
    day_assigned: 145,
    day_due: 145,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 354,
    object_name: 'Homework 354',
    day_assigned: 146,
    day_due: 146,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 355,
    object_name: 'Homework 355',
    day_assigned: 146,
    day_due: 146,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 356,
    object_name: 'Homework 356',
    day_assigned: 147,
    day_due: 147,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 357,
    object_name: 'Homework 357',
    day_assigned: 147,
    day_due: 147,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 358,
    object_name: 'Homework 358',
    day_assigned: 148,
    day_due: 148,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 359,
    object_name: 'Homework 359',
    day_assigned: 148,
    day_due: 148,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 360,
    object_name: 'Homework 360',
    day_assigned: 148,
    day_due: 148,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 361,
    object_name: 'Homework 361',
    day_assigned: 149,
    day_due: 149,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 362,
    object_name: 'Homework 362',
    day_assigned: 149,
    day_due: 149,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 363,
    object_name: 'Homework 363',
    day_assigned: 150,
    day_due: 150,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 364,
    object_name: 'Homework 364',
    day_assigned: 150,
    day_due: 150,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 365,
    object_name: 'Homework 365',
    day_assigned: 150,
    day_due: 150,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 366,
    object_name: 'Homework 366',
    day_assigned: 151,
    day_due: 151,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 367,
    object_name: 'Homework 367',
    day_assigned: 151,
    day_due: 151,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 368,
    object_name: 'Homework 368',
    day_assigned: 152,
    day_due: 152,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 369,
    object_name: 'Homework 369',
    day_assigned: 152,
    day_due: 152,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 370,
    object_name: 'Homework 370',
    day_assigned: 152,
    day_due: 152,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 371,
    object_name: 'Homework 371',
    day_assigned: 153,
    day_due: 153,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 372,
    object_name: 'Homework 372',
    day_assigned: 153,
    day_due: 153,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 373,
    object_name: 'Homework 373',
    day_assigned: 154,
    day_due: 154,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 374,
    object_name: 'Homework 374',
    day_assigned: 154,
    day_due: 154,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 375,
    object_name: 'Homework 375',
    day_assigned: 155,
    day_due: 155,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 376,
    object_name: 'Homework 376',
    day_assigned: 155,
    day_due: 155,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 377,
    object_name: 'Homework 377',
    day_assigned: 155,
    day_due: 155,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 378,
    object_name: 'Homework 378',
    day_assigned: 156,
    day_due: 156,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 379,
    object_name: 'Homework 379',
    day_assigned: 156,
    day_due: 156,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 380,
    object_name: 'Homework 380',
    day_assigned: 157,
    day_due: 157,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 381,
    object_name: 'Homework 381',
    day_assigned: 157,
    day_due: 157,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 382,
    object_name: 'Homework 382',
    day_assigned: 157,
    day_due: 157,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 383,
    object_name: 'Homework 383',
    day_assigned: 158,
    day_due: 158,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 384,
    object_name: 'Homework 384',
    day_assigned: 158,
    day_due: 158,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 385,
    object_name: 'Homework 385',
    day_assigned: 159,
    day_due: 159,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 386,
    object_name: 'Homework 386',
    day_assigned: 159,
    day_due: 159,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 387,
    object_name: 'Homework 387',
    day_assigned: 159,
    day_due: 159,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 388,
    object_name: 'Homework 388',
    day_assigned: 160,
    day_due: 160,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 389,
    object_name: 'Homework 389',
    day_assigned: 160,
    day_due: 160,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 390,
    object_name: 'Homework 390',
    day_assigned: 161,
    day_due: 161,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 391,
    object_name: 'Homework 391',
    day_assigned: 161,
    day_due: 161,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 392,
    object_name: 'Homework 392',
    day_assigned: 162,
    day_due: 162,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 393,
    object_name: 'Homework 393',
    day_assigned: 162,
    day_due: 162,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 394,
    object_name: 'Homework 394',
    day_assigned: 162,
    day_due: 162,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 395,
    object_name: 'Homework 395',
    day_assigned: 163,
    day_due: 163,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 396,
    object_name: 'Homework 396',
    day_assigned: 163,
    day_due: 163,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 397,
    object_name: 'Homework 397',
    day_assigned: 164,
    day_due: 164,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 398,
    object_name: 'Homework 398',
    day_assigned: 164,
    day_due: 164,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 399,
    object_name: 'Homework 399',
    day_assigned: 164,
    day_due: 164,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 400,
    object_name: 'Homework 400',
    day_assigned: 165,
    day_due: 165,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 401,
    object_name: 'Homework 401',
    day_assigned: 165,
    day_due: 165,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 402,
    object_name: 'Homework 402',
    day_assigned: 166,
    day_due: 166,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 403,
    object_name: 'Homework 403',
    day_assigned: 166,
    day_due: 166,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 404,
    object_name: 'Homework 404',
    day_assigned: 166,
    day_due: 166,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 405,
    object_name: 'Homework 405',
    day_assigned: 167,
    day_due: 167,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 406,
    object_name: 'Homework 406',
    day_assigned: 167,
    day_due: 167,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 407,
    object_name: 'Homework 407',
    day_assigned: 168,
    day_due: 168,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 408,
    object_name: 'Homework 408',
    day_assigned: 168,
    day_due: 168,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 409,
    object_name: 'Homework 409',
    day_assigned: 169,
    day_due: 169,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 410,
    object_name: 'Homework 410',
    day_assigned: 169,
    day_due: 169,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 411,
    object_name: 'Homework 411',
    day_assigned: 169,
    day_due: 169,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 412,
    object_name: 'Homework 412',
    day_assigned: 170,
    day_due: 170,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 413,
    object_name: 'Homework 413',
    day_assigned: 170,
    day_due: 170,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 414,
    object_name: 'Homework 414',
    day_assigned: 171,
    day_due: 171,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 415,
    object_name: 'Homework 415',
    day_assigned: 171,
    day_due: 171,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 416,
    object_name: 'Homework 416',
    day_assigned: 171,
    day_due: 171,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 417,
    object_name: 'Homework 417',
    day_assigned: 172,
    day_due: 172,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 418,
    object_name: 'Homework 418',
    day_assigned: 172,
    day_due: 172,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 419,
    object_name: 'Homework 419',
    day_assigned: 173,
    day_due: 173,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 420,
    object_name: 'Homework 420',
    day_assigned: 173,
    day_due: 173,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 421,
    object_name: 'Homework 421',
    day_assigned: 173,
    day_due: 173,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 422,
    object_name: 'Homework 422',
    day_assigned: 174,
    day_due: 174,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 423,
    object_name: 'Homework 423',
    day_assigned: 174,
    day_due: 174,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 424,
    object_name: 'Homework 424',
    day_assigned: 175,
    day_due: 175,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 425,
    object_name: 'Homework 425',
    day_assigned: 175,
    day_due: 175,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 426,
    object_name: 'Homework 426',
    day_assigned: 176,
    day_due: 176,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 427,
    object_name: 'Homework 427',
    day_assigned: 176,
    day_due: 176,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 428,
    object_name: 'Homework 428',
    day_assigned: 176,
    day_due: 176,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 429,
    object_name: 'Homework 429',
    day_assigned: 177,
    day_due: 177,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' },
  { id: 430,
    object_name: 'Homework 430',
    day_assigned: 177,
    day_due: 177,
    file_id: '0',
    percent_of_module_grade: '.01',
    type_id: '1' }];

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => knex(tableName).del())
    .then(() => Promise.all(data.map(type => knex(tableName).insert(type))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
