exports.seed = (knex, Promise) => {
  const tableName = 'graph_data';
  const data = [{ department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 1,
    gradeableobject_id: 1,
    student_id: 5,
    grade: 93 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    student_id: 5,
    grade: 92 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 2,
    gradeableobject_id: 1,
    student_id: 1,
    grade: 83 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 2,
    student_id: 2,
    grade: 78 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 3,
    gradeableobject_id: 1,
    student_id: 4,
    grade: 72 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 3,
    student_id: 6,
    grade: 70 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 4,
    student_id: 6,
    grade: 90 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 5,
    student_id: 2,
    grade: 70 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 6,
    student_id: 5,
    grade: 79 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 7,
    student_id: 4,
    grade: 80 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 8,
    student_id: 6,
    grade: 75 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 9,
    student_id: 3,
    grade: 91 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 10,
    student_id: 5,
    grade: 72 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 11,
    student_id: 3,
    grade: 66 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 12,
    student_id: 3,
    grade: 77 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 13,
    student_id: 2,
    grade: 65 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 14,
    student_id: 5,
    grade: 94 },
  { department_id: 1,
    course_id: 1,
    class_id: 1,
    module_id: 4,
    gradeableobject_id: 1,
    student_id: 1,
    grade: 97 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 1,
    student_id: 7,
    grade: 67 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    student_id: 6,
    grade: 78 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 3,
    student_id: 2,
    grade: 79 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 4,
    module_id: 5,
    student_id: 7,
    grade: 93 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 5,
    student_id: 4,
    grade: 83 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 5,
    module_id: 6,
    student_id: 1,
    grade: 83 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 6,
    student_id: 2,
    grade: 94 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 6,
    module_id: 7,
    student_id: 3,
    grade: 85 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 7,
    student_id: 6,
    grade: 99 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 7,
    module_id: 8,
    student_id: 5,
    grade: 86 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 8,
    module_id: 8,
    student_id: 4,
    grade: 66 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 9,
    module_id: 8,
    student_id: 5,
    grade: 67 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 10,
    module_id: 8,
    student_id: 6,
    grade: 84 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 11,
    module_id: 8,
    student_id: 6,
    grade: 75 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 12,
    module_id: 8,
    student_id: 6,
    grade: 96 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 13,
    module_id: 8,
    student_id: 3,
    grade: 90 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 14,
    module_id: 8,
    student_id: 5,
    grade: 97 },
  { department_id: 2,
    course_id: 2,
    class_id: 2,
    gradeableobject_id: 2,
    module_id: 8,
    student_id: 1,
    grade: 95 },
  { department_id: 3,
    course_id: 3,
    class_id: 3,
    student_id: 6,
    grade: 68 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 1,
    student_id: 2,
    grade: 87 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 2,
    student_id: 6,
    grade: 66 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 3,
    student_id: 4,
    grade: 69 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    student_id: 3,
    grade: 95 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 5,
    student_id: 5,
    grade: 91 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 6,
    student_id: 5,
    grade: 80 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 7,
    student_id: 2,
    grade: 74 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 8,
    module_id: 9,
    student_id: 3,
    grade: 80 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 9,
    student_id: 5,
    grade: 91 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 9,
    module_id: 10,
    student_id: 2,
    grade: 86 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 10,
    student_id: 5,
    grade: 98 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 10,
    module_id: 11,
    student_id: 6,
    grade: 92 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 11,
    student_id: 5,
    grade: 70 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 11,
    module_id: 12,
    student_id: 3,
    grade: 85 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 12,
    module_id: 12,
    student_id: 5,
    grade: 89 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 13,
    module_id: 12,
    student_id: 6,
    grade: 82 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 14,
    module_id: 12,
    student_id: 5,
    grade: 86 },
  { department_id: 3,
    course_id: 3,
    class_id: 4,
    gradeableobject_id: 4,
    module_id: 12,
    student_id: 5,
    grade: 81 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 1,
    student_id: 5,
    grade: 98 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 2,
    student_id: 3,
    grade: 88 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 3,
    student_id: 3,
    grade: 77 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 4,
    student_id: 6,
    grade: 79 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    student_id: 6,
    grade: 86 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 6,
    student_id: 6,
    grade: 71 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 7,
    student_id: 4,
    grade: 75 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 8,
    student_id: 5,
    grade: 66 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 9,
    student_id: 7,
    grade: 74 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 10,
    student_id: 5,
    grade: 79 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 11,
    student_id: 4,
    grade: 83 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 12,
    module_id: 13,
    student_id: 2,
    grade: 80 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 13,
    student_id: 2,
    grade: 69 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 13,
    module_id: 14,
    student_id: 3,
    grade: 75 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 14,
    student_id: 4,
    grade: 93 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 14,
    module_id: 15,
    student_id: 4,
    grade: 71 },
  { department_id: 4,
    course_id: 4,
    class_id: 5,
    gradeableobject_id: 5,
    module_id: 15,
    student_id: 4,
    grade: 69 }];

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => knex(tableName).del())
    .then(() => Promise.all(data.map(type => knex(tableName).insert(type))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
